select * from BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG;

SELECT RULE_ID, ERROR_MESSAGE
FROM BANKING_DQ_DB.DQ_MONITORING.DQ_RUN_CONTROL
WHERE RUN_ID = 'RUN_20260920_003548_6057' AND RUN_STATUS = 'FAILED'
LIMIT 5