/*=============================================================================
  DQ_cleanup.sql
  Data Quality Framework - Step 8: Cleanup Script
  
  WARNING: This script drops ALL objects created by the DQ Framework POC.
  Review carefully before executing. This is irreversible.
  
  Execution order matters — drop in reverse dependency order:
    1. DMF associations (detach from tables)
    2. Custom DMF functions
    3. Framework stored procedure
    4. Framework tables (DQ_MONITORING schema)
    5. Framework schema
    6. Data metric schedules (unset from source tables)
=============================================================================*/

USE DATABASE BANKING_DQ_DB;

-- ============================================================================
-- PART 1: DETACH ALL DMFs FROM TABLES
-- ============================================================================

-- 1.1 BRANCHES — detach system DMFs
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_ID);
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_NAME);
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (IFSC_CODE);
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (BRANCH_ID);
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (IFSC_CODE);
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (STATE);
ALTER TABLE RAW.BRANCHES DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_IFSC_FORMAT ON (IFSC_CODE);

-- 1.2 CUSTOMERS — detach system + custom DMFs
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PHONE);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (DATE_OF_BIRTH);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (EMAIL);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT ON (BRANCH_ID, TABLE(BANKING_DQ_DB.RAW.BRANCHES(BRANCH_ID)));
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (KYC_STATUS);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (RISK_CATEGORY);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_EMAIL_FORMAT ON (EMAIL);
ALTER TABLE RAW.CUSTOMERS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_PHONE_FORMAT ON (PHONE);

-- 1.3 ACCOUNTS — detach system + custom DMFs
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BALANCE);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ACCOUNT_ID);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT ON (CUSTOMER_ID, TABLE(BANKING_DQ_DB.RAW.CUSTOMERS(CUSTOMER_ID)));
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT ON (BRANCH_ID, TABLE(BANKING_DQ_DB.RAW.BRANCHES(BRANCH_ID)));
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (ACCOUNT_TYPE);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (ACCOUNT_STATUS);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (CURRENCY);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_SAVINGS_BALANCE_NON_NEG ON (ACCOUNT_TYPE, BALANCE);
ALTER TABLE RAW.ACCOUNTS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_CLOSED_ZERO_BALANCE ON (ACCOUNT_STATUS, BALANCE);

-- 1.4 TRANSACTIONS — detach system + custom DMFs
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_ID);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AMOUNT);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_DATE);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRANSACTION_ID);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT ON (ACCOUNT_ID, TABLE(BANKING_DQ_DB.RAW.ACCOUNTS(ACCOUNT_ID)));
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (TRANSACTION_TYPE);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (TRANSACTION_STATUS);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (CHANNEL);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (AMOUNT);
ALTER TABLE RAW.TRANSACTIONS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_AMOUNT_RANGE ON (AMOUNT);

-- 1.5 LOAN_APPLICATIONS — detach system + custom DMFs
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (APPLICATION_ID);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (REQUESTED_AMOUNT);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CREDIT_SCORE);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (APPLICATION_ID);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT ON (CUSTOMER_ID, TABLE(BANKING_DQ_DB.RAW.CUSTOMERS(CUSTOMER_ID)));
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT ON (BRANCH_ID, TABLE(BANKING_DQ_DB.RAW.BRANCHES(BRANCH_ID)));
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (APPLICATION_STATUS);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (LOAN_TYPE);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (REQUESTED_AMOUNT);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (CREDIT_SCORE);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_HAS_AMOUNT ON (APPLICATION_STATUS, APPROVED_AMOUNT);
ALTER TABLE RAW.LOAN_APPLICATIONS DROP DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_LTE_REQUESTED ON (APPROVED_AMOUNT, REQUESTED_AMOUNT);

-- ============================================================================
-- PART 2: UNSET DATA METRIC SCHEDULES
-- ============================================================================
ALTER TABLE RAW.BRANCHES UNSET DATA_METRIC_SCHEDULE;
ALTER TABLE RAW.CUSTOMERS UNSET DATA_METRIC_SCHEDULE;
ALTER TABLE RAW.ACCOUNTS UNSET DATA_METRIC_SCHEDULE;
ALTER TABLE RAW.TRANSACTIONS UNSET DATA_METRIC_SCHEDULE;
ALTER TABLE RAW.LOAN_APPLICATIONS UNSET DATA_METRIC_SCHEDULE;

-- ============================================================================
-- PART 3: DROP CUSTOM DMF FUNCTIONS
-- ============================================================================
DROP FUNCTION IF EXISTS RAW.DMF_IFSC_FORMAT(TABLE(VARCHAR));
DROP FUNCTION IF EXISTS RAW.DMF_EMAIL_FORMAT(TABLE(VARCHAR));
DROP FUNCTION IF EXISTS RAW.DMF_PHONE_FORMAT(TABLE(VARCHAR));
DROP FUNCTION IF EXISTS RAW.DMF_SAVINGS_BALANCE_NON_NEG(TABLE(VARCHAR, NUMBER));
DROP FUNCTION IF EXISTS RAW.DMF_CLOSED_ZERO_BALANCE(TABLE(VARCHAR, NUMBER));
DROP FUNCTION IF EXISTS RAW.DMF_AMOUNT_RANGE(TABLE(NUMBER));
DROP FUNCTION IF EXISTS RAW.DMF_APPROVED_HAS_AMOUNT(TABLE(VARCHAR, NUMBER));
DROP FUNCTION IF EXISTS RAW.DMF_APPROVED_LTE_REQUESTED(TABLE(NUMBER, NUMBER));

-- ============================================================================
-- PART 4: DROP FRAMEWORK STORED PROCEDURE
-- ============================================================================
DROP PROCEDURE IF EXISTS DQ_MONITORING.SP_RUN_DQ_FRAMEWORK(VARCHAR);

-- ============================================================================
-- PART 5: DROP FRAMEWORK TABLES
-- ============================================================================
DROP TABLE IF EXISTS DQ_MONITORING.DQ_RULE_CONFIG;
DROP TABLE IF EXISTS DQ_MONITORING.DQ_RUN_CONTROL;
DROP TABLE IF EXISTS DQ_MONITORING.DQ_RULE_RESULTS;
DROP TABLE IF EXISTS DQ_MONITORING.DQ_ERROR_RECORDS;
DROP TABLE IF EXISTS DQ_MONITORING.DQ_ANOMALY_RESULTS;

-- ============================================================================
-- PART 6: DROP FRAMEWORK SCHEMA
-- ============================================================================
DROP SCHEMA IF EXISTS DQ_MONITORING;

-- ============================================================================
-- VERIFICATION: Confirm cleanup
-- ============================================================================
-- Check no DMFs remain on tables
SELECT 'BRANCHES' AS TBL, COUNT(*) AS DMFS FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.BRANCHES', REF_ENTITY_DOMAIN => 'table'))
UNION ALL SELECT 'CUSTOMERS', COUNT(*) FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.CUSTOMERS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL SELECT 'ACCOUNTS', COUNT(*) FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.ACCOUNTS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL SELECT 'TRANSACTIONS', COUNT(*) FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.TRANSACTIONS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL SELECT 'LOAN_APPLICATIONS', COUNT(*) FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.LOAN_APPLICATIONS', REF_ENTITY_DOMAIN => 'table'));

-- Check schema is dropped
SHOW SCHEMAS LIKE 'DQ_MONITORING' IN DATABASE BANKING_DQ_DB;

/*=============================================================================
  NOTE: This script does NOT drop:
  - BANKING_DQ_DB database (contains source data)
  - RAW schema or any source tables (BRANCHES, CUSTOMERS, ACCOUNTS, etc.)
  - The Streamlit app folder (dq-monitoring-dashboard/) — delete manually from workspace
  - The workspace SQL script files — delete manually if needed
=============================================================================*/
