/*=============================================================================
  DQ_Framework_Config.sql
  Data Quality Framework - Step 4: Framework Schema, Tables & Config Load
  Database: BANKING_DQ_DB | Schema: DQ_MONITORING
  
  Objects Created:
    - Schema: DQ_MONITORING
    - Tables: DQ_RULE_CONFIG, DQ_RUN_CONTROL, DQ_RULE_RESULTS,
              DQ_ERROR_RECORDS, DQ_ANOMALY_RESULTS
    - Data:   61 rules loaded into DQ_RULE_CONFIG (all plain SQL)
  
  RULE_SQL CONVENTION:
    Every RULE_SQL is a complete, executable SELECT returning a single NUMBER.
    - Violation rules return COUNT of bad rows (0 = pass)
    - ROW_COUNT rules return total rows (always pass, used for anomaly detection)
    No DMF function calls — all plain SQL for portability and debuggability.
=============================================================================*/

-- ============================================================================
-- PART 1: CREATE SCHEMA
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS BANKING_DQ_DB.DQ_MONITORING;

-- ============================================================================
-- PART 2: CREATE FRAMEWORK TABLES
-- ============================================================================

-- 2.1 DQ_RULE_CONFIG: Stores all data quality rule definitions
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (
    RULE_ID        VARCHAR(50) NOT NULL,
    RULE_NAME      VARCHAR(200) NOT NULL,
    RULE_TYPE      VARCHAR(50) NOT NULL,
    FREQUENCY      VARCHAR(50) DEFAULT 'TRIGGER_ON_CHANGES',
    CRITICALITY    VARCHAR(20) NOT NULL,
    DB_NAME        VARCHAR(200) NOT NULL,
    TABLE_NM       VARCHAR(200) NOT NULL,
    COLUMN_NM      VARCHAR(200),
    RULE_DESCRIPTION VARCHAR(1000),
    RULE_SQL       VARCHAR(4000),
    THRESHOLD_VALUE NUMBER(18,4) DEFAULT 0,
    RULE_DIMENSION VARIANT,
    IS_ACTIVE      BOOLEAN DEFAULT TRUE,
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2.2 DQ_RUN_CONTROL: Tracks each execution run
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RUN_CONTROL (
    RUN_ID           VARCHAR(50) NOT NULL,
    RULE_ID          VARCHAR(50) NOT NULL,
    RUN_START_TIME   TIMESTAMP_NTZ,
    RUN_END_TIME     TIMESTAMP_NTZ,
    RULE_EXEC_RESULT VARCHAR(20),
    RULE_OUTPUT_VALUE NUMBER(18,4),
    RUN_STATUS       VARCHAR(20) DEFAULT 'PENDING',
    TRIGGERED_BY     VARCHAR(100) DEFAULT 'MANUAL',
    ERROR_MESSAGE    VARCHAR(2000),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2.3 DQ_RULE_RESULTS: Stores rule-level execution results
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_RESULTS (
    RESULT_ID          VARCHAR(50) NOT NULL,
    RUN_ID             VARCHAR(50) NOT NULL,
    RULE_ID            VARCHAR(50) NOT NULL,
    DB_NAME            VARCHAR(200),
    TABLE_NAME         VARCHAR(200),
    COLUMN_NAME        VARCHAR(200),
    RULE_NAME          VARCHAR(200),
    RULE_TYPE          VARCHAR(50),
    EXPECTED_VALUE     NUMBER(18,4),
    ACTUAL_VALUE       NUMBER(18,4),
    FAILED_RECORD_COUNT NUMBER(18,0),
    TOTAL_RECORD_COUNT  NUMBER(18,0),
    PASS_PERCENTAGE    NUMBER(7,2),
    RESULT_STATUS      VARCHAR(20),
    SEVERITY           VARCHAR(20),
    ERROR_SAMPLE_QUERY VARCHAR(4000),
    EXECUTED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2.4 DQ_ERROR_RECORDS: Stores detailed failed/sample records
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ERROR_RECORDS (
    ERROR_ID             VARCHAR(50) NOT NULL,
    RUN_ID               VARCHAR(50) NOT NULL,
    RULE_ID              VARCHAR(50) NOT NULL,
    DB_NAME              VARCHAR(200),
    TABLE_NAME           VARCHAR(200),
    ERROR_RECORD_VARIANT VARIANT,
    ERROR_REASON         VARCHAR(1000),
    CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2.5 DQ_ANOMALY_RESULTS: Stores anomaly detection results
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ANOMALY_RESULTS (
    ANOMALY_ID       VARCHAR(50) NOT NULL,
    RUN_ID           VARCHAR(50) NOT NULL,
    DATABASE_NAME    VARCHAR(200),
    SCHEMA_NAME      VARCHAR(200),
    TABLE_NAME       VARCHAR(200),
    METRIC_NAME      VARCHAR(200),
    CURRENT_VALUE    NUMBER(18,4),
    PREVIOUS_VALUE   NUMBER(18,4),
    BASELINE_AVG     NUMBER(18,4),
    BASELINE_STDDEV  NUMBER(18,4),
    ANOMALY_STATUS   VARCHAR(50),
    ANOMALY_REASON   VARCHAR(1000),
    DETECTED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- PART 3: LOAD RULES INTO DQ_RULE_CONFIG (all plain SQL)
-- ============================================================================

-- 3.1 BRANCHES rules (8 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'BR-T01','BRANCHES_NULL_COUNT_BRANCH_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_ID','NULL count on PK BRANCH_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE BRANCH_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR-T02','BRANCHES_DUPLICATE_COUNT_BRANCH_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_ID','Duplicate count on PK BRANCH_ID','SELECT COUNT(*) - COUNT(DISTINCT BRANCH_ID) FROM BANKING_DQ_DB.RAW.BRANCHES',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'BR-T03','BRANCHES_NULL_COUNT_BRANCH_NAME','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_NAME','NULL count on BRANCH_NAME','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE BRANCH_NAME IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR-T04','BRANCHES_NULL_COUNT_IFSC_CODE','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','BRANCHES','IFSC_CODE','NULL count on IFSC_CODE','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE IFSC_CODE IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR-T05','BRANCHES_ROW_COUNT','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','BRANCHES',NULL,'Row count volume monitoring','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR-T06','BRANCHES_DUPLICATE_COUNT_IFSC','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','BRANCHES','IFSC_CODE','Duplicate count on IFSC_CODE','SELECT COUNT(*) - COUNT(DISTINCT IFSC_CODE) FROM BANKING_DQ_DB.RAW.BRANCHES',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'BR-B01','BRANCHES_IFSC_FORMAT','CUSTOM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','BRANCHES','IFSC_CODE','IFSC format: 4 alpha + 0 + 6 alphanum','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE IFSC_CODE IS NOT NULL AND NOT RLIKE(IFSC_CODE, ''^[A-Z]{4}0[A-Z0-9]{6}$'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'BR-B02','BRANCHES_STATE_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','BRANCHES','STATE','STATE must not be NULL or empty','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE STATE IS NULL OR LENGTH(TRIM(STATE)) = 0',0,PARSE_JSON('["completeness"]'),TRUE;

-- 3.2 CUSTOMERS rules (13 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'CU-T01','CUSTOMERS_NULL_COUNT_CUSTOMER_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','CUSTOMER_ID','NULL count on PK CUSTOMER_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE CUSTOMER_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU-T02','CUSTOMERS_DUPLICATE_COUNT_CUST_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','CUSTOMER_ID','Duplicate count on PK CUSTOMER_ID','SELECT COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) FROM BANKING_DQ_DB.RAW.CUSTOMERS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'CU-T03','CUSTOMERS_NULL_COUNT_EMAIL','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','NULL count on EMAIL','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE EMAIL IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU-T04','CUSTOMERS_DUPLICATE_COUNT_EMAIL','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','Duplicate count on EMAIL','SELECT COUNT(*) - COUNT(DISTINCT EMAIL) FROM BANKING_DQ_DB.RAW.CUSTOMERS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'CU-T05','CUSTOMERS_NULL_COUNT_PHONE','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS','PHONE','NULL count on PHONE','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE PHONE IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU-T06','CUSTOMERS_NULL_COUNT_DOB','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS','DATE_OF_BIRTH','NULL count on DATE_OF_BIRTH','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE DATE_OF_BIRTH IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU-T07','CUSTOMERS_ROW_COUNT','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS',NULL,'Row count volume monitoring','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU-B01','CUSTOMERS_EMAIL_FORMAT','CUSTOM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','EMAIL must contain @ and .','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE EMAIL IS NOT NULL AND EMAIL NOT LIKE ''%_@_%.__%''',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU-B02','CUSTOMERS_KYC_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','KYC_STATUS','KYC_STATUS in (VERIFIED,PENDING,REJECTED)','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE KYC_STATUS NOT IN (''VERIFIED'',''PENDING'',''REJECTED'')',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'CU-B03','CUSTOMERS_RISK_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','RISK_CATEGORY','RISK_CATEGORY in (LOW,MEDIUM,HIGH)','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE RISK_CATEGORY NOT IN (''LOW'',''MEDIUM'',''HIGH'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU-B04','CUSTOMERS_DOB_RANGE','BUSINESS_RULE','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS','DATE_OF_BIRTH','Age must be 18-120 years','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE DATE_OF_BIRTH IS NOT NULL AND (DATEDIFF(YEAR,DATE_OF_BIRTH,CURRENT_DATE())<18 OR DATEDIFF(YEAR,DATE_OF_BIRTH,CURRENT_DATE())>120)',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'CU-B05','CUSTOMERS_BRANCH_FK','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','BRANCH_ID','BRANCH_ID must exist in BRANCHES','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS C LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES B ON C.BRANCH_ID=B.BRANCH_ID WHERE B.BRANCH_ID IS NULL',0,PARSE_JSON('["integrity"]'),TRUE
UNION ALL SELECT 'CU-B06','CUSTOMERS_PHONE_FORMAT','CUSTOM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS','PHONE','PHONE must have 10+ digits','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE PHONE IS NOT NULL AND LENGTH(REGEXP_REPLACE(PHONE, ''[^0-9]'', '''')) < 10',0,PARSE_JSON('["validity"]'),TRUE;

-- 3.3 ACCOUNTS rules (12 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'AC-T01','ACCOUNTS_NULL_COUNT_ACCOUNT_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_ID','NULL count on PK ACCOUNT_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC-T02','ACCOUNTS_DUPLICATE_COUNT_ACCOUNT_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_ID','Duplicate count on PK ACCOUNT_ID','SELECT COUNT(*) - COUNT(DISTINCT ACCOUNT_ID) FROM BANKING_DQ_DB.RAW.ACCOUNTS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'AC-T03','ACCOUNTS_NULL_COUNT_CUSTOMER_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','CUSTOMER_ID','NULL count on FK CUSTOMER_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE CUSTOMER_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC-T04','ACCOUNTS_NULL_COUNT_BALANCE','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BALANCE','NULL count on BALANCE','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE BALANCE IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC-T05','ACCOUNTS_ROW_COUNT','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','ACCOUNTS',NULL,'Row count volume monitoring','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC-B01','ACCOUNTS_TYPE_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_TYPE','ACCOUNT_TYPE in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_TYPE NOT IN (''SAVINGS'',''CURRENT'',''LOAN'',''FD'',''RD'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'AC-B02','ACCOUNTS_STATUS_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_STATUS','ACCOUNT_STATUS in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_STATUS NOT IN (''ACTIVE'',''CLOSED'',''DORMANT'',''FROZEN'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'AC-B03','ACCOUNTS_SAVINGS_BALANCE_NON_NEG','CUSTOM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BALANCE','SAVINGS accounts must have BALANCE >= 0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_TYPE = ''SAVINGS'' AND BALANCE < 0',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'AC-B04','ACCOUNTS_CURRENCY_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','ACCOUNTS','CURRENCY','CURRENCY in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE CURRENCY NOT IN (''INR'',''USD'',''EUR'',''GBP'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'AC-B05','ACCOUNTS_CUSTOMER_FK','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','CUSTOMER_ID','CUSTOMER_ID must exist in CUSTOMERS','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS A LEFT JOIN BANKING_DQ_DB.RAW.CUSTOMERS C ON A.CUSTOMER_ID=C.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL',0,PARSE_JSON('["integrity"]'),TRUE
UNION ALL SELECT 'AC-B06','ACCOUNTS_BRANCH_FK','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BRANCH_ID','BRANCH_ID must exist in BRANCHES','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS A LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES B ON A.BRANCH_ID=B.BRANCH_ID WHERE B.BRANCH_ID IS NULL',0,PARSE_JSON('["integrity"]'),TRUE
UNION ALL SELECT 'AC-B07','ACCOUNTS_CLOSED_ZERO_BALANCE','CUSTOM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','ACCOUNTS','BALANCE','CLOSED accounts should have BALANCE=0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_STATUS = ''CLOSED'' AND BALANCE != 0',0,PARSE_JSON('["consistency"]'),TRUE;

-- 3.4 TRANSACTIONS rules (13 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'TX-T01','TXNS_NULL_COUNT_TRANSACTION_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_ID','NULL count on PK TRANSACTION_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX-T02','TXNS_DUPLICATE_COUNT_TRANSACTION_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_ID','Duplicate count on PK','SELECT COUNT(*) - COUNT(DISTINCT TRANSACTION_ID) FROM BANKING_DQ_DB.RAW.TRANSACTIONS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'TX-T03','TXNS_NULL_COUNT_ACCOUNT_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','ACCOUNT_ID','NULL count on FK ACCOUNT_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE ACCOUNT_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX-T04','TXNS_NULL_COUNT_AMOUNT','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','AMOUNT','NULL count on AMOUNT','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE AMOUNT IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX-T05','TXNS_NULL_COUNT_TRANSACTION_DATE','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_DATE','NULL count on TRANSACTION_DATE','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_DATE IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX-T06','TXNS_ROW_COUNT','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS',NULL,'Row count - high-volume table','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX-B01','TXNS_AMOUNT_POSITIVE','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','AMOUNT','AMOUNT must be > 0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE AMOUNT <= 0',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'TX-B02','TXNS_TYPE_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_TYPE','TRANSACTION_TYPE in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_TYPE NOT IN (''CREDIT'',''DEBIT'',''TRANSFER'',''PAYMENT'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'TX-B03','TXNS_STATUS_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_STATUS','TRANSACTION_STATUS in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_STATUS NOT IN (''SUCCESS'',''FAILED'',''PENDING'',''REVERSED'')',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'TX-B04','TXNS_CHANNEL_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','TRANSACTIONS','CHANNEL','CHANNEL in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE CHANNEL NOT IN (''UPI'',''NEFT'',''IMPS'',''RTGS'',''CARD'',''ATM'',''CHEQUE'',''BRANCH'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'TX-B05','TXNS_ACCOUNT_FK','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','ACCOUNT_ID','ACCOUNT_ID must exist in ACCOUNTS','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS T LEFT JOIN BANKING_DQ_DB.RAW.ACCOUNTS A ON T.ACCOUNT_ID=A.ACCOUNT_ID WHERE A.ACCOUNT_ID IS NULL',0,PARSE_JSON('["integrity"]'),TRUE
UNION ALL SELECT 'TX-B06','TXNS_DATE_NOT_FUTURE','BUSINESS_RULE','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_DATE','TRANSACTION_DATE must not be future','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_DATE > CURRENT_TIMESTAMP()',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'TX-B07','TXNS_AMOUNT_RANGE','CUSTOM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','TRANSACTIONS','AMOUNT','AMOUNT <= 10M outlier check','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE AMOUNT IS NOT NULL AND AMOUNT > 10000000',0,PARSE_JSON('["accuracy"]'),TRUE;

-- 3.5 LOAN_APPLICATIONS rules (15 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'LA-T01','LOANS_NULL_COUNT_APPLICATION_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_ID','NULL count on PK APPLICATION_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA-T02','LOANS_DUPLICATE_COUNT_APPLICATION_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_ID','Duplicate count on PK','SELECT COUNT(*) - COUNT(DISTINCT APPLICATION_ID) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'LA-T03','LOANS_NULL_COUNT_CUSTOMER_ID','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CUSTOMER_ID','NULL count on FK CUSTOMER_ID','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE CUSTOMER_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA-T04','LOANS_NULL_COUNT_REQUESTED_AMT','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','REQUESTED_AMOUNT','NULL count on REQUESTED_AMOUNT','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE REQUESTED_AMOUNT IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA-T05','LOANS_NULL_COUNT_CREDIT_SCORE','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CREDIT_SCORE','NULL count on CREDIT_SCORE','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE CREDIT_SCORE IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA-T06','LOANS_ROW_COUNT','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS',NULL,'Row count volume monitoring','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA-B01','LOANS_REQUESTED_AMT_POSITIVE','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','REQUESTED_AMOUNT','REQUESTED_AMOUNT must be > 0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE REQUESTED_AMOUNT <= 0',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'LA-B02','LOANS_APPROVED_LTE_REQUESTED','CUSTOM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPROVED_AMOUNT','APPROVED_AMOUNT <= REQUESTED_AMOUNT','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPROVED_AMOUNT IS NOT NULL AND REQUESTED_AMOUNT IS NOT NULL AND APPROVED_AMOUNT > REQUESTED_AMOUNT',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'LA-B03','LOANS_CREDIT_SCORE_RANGE','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CREDIT_SCORE','CREDIT_SCORE between 300 and 900','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE CREDIT_SCORE < 300 OR CREDIT_SCORE > 900',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA-B04','LOANS_STATUS_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_STATUS','APPLICATION_STATUS in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_STATUS NOT IN (''APPROVED'',''PENDING'',''REJECTED'',''CANCELLED'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA-B05','LOANS_TYPE_ACCEPTED_VALUES','SYSTEM_DMF','TRIGGER_ON_CHANGES','MEDIUM','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','LOAN_TYPE','LOAN_TYPE in allowed set','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE LOAN_TYPE NOT IN (''HOME'',''PERSONAL'',''CAR'',''EDUCATION'',''BUSINESS'',''GOLD'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA-B06','LOANS_APPROVED_HAS_AMOUNT','CUSTOM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPROVED_AMOUNT','APPROVED status must have APPROVED_AMOUNT','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_STATUS = ''APPROVED'' AND APPROVED_AMOUNT IS NULL',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'LA-B07','LOANS_CUSTOMER_FK','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CUSTOMER_ID','CUSTOMER_ID must exist in CUSTOMERS','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS L LEFT JOIN BANKING_DQ_DB.RAW.CUSTOMERS C ON L.CUSTOMER_ID=C.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL',0,PARSE_JSON('["integrity"]'),TRUE
UNION ALL SELECT 'LA-B08','LOANS_BRANCH_FK','SYSTEM_DMF','TRIGGER_ON_CHANGES','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','BRANCH_ID','BRANCH_ID must exist in BRANCHES','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS L LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES B ON L.BRANCH_ID=B.BRANCH_ID WHERE B.BRANCH_ID IS NULL',0,PARSE_JSON('["integrity"]'),TRUE
UNION ALL SELECT 'LA-B09','LOANS_DATE_NOT_FUTURE','BUSINESS_RULE','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_DATE','APPLICATION_DATE must not be future','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_DATE > CURRENT_DATE()',0,PARSE_JSON('["accuracy"]'),TRUE;

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SELECT TABLE_NM, RULE_TYPE, CRITICALITY, COUNT(*) AS RULE_COUNT
FROM BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
GROUP BY TABLE_NM, RULE_TYPE, CRITICALITY
ORDER BY TABLE_NM, RULE_TYPE, CRITICALITY;

/*=============================================================================
  END OF DQ FRAMEWORK CONFIG
=============================================================================*/
