/*=============================================================================
  DQ_Rules.sql
  Data Quality Framework - Step 3: Create and Attach Data Quality Rules
  Database: BANKING_DQ_DB | Schema: RAW
  
  Total DMF Associations: 59
  - System DMFs: NULL_COUNT, DUPLICATE_COUNT, ROW_COUNT, ACCEPTED_VALUES, 
                 REFERENTIAL_INTEGRITY_COUNT
  - Custom DMFs: 8 cross-column/format validation functions
  
  Note: FRESHNESS DMF not available in this account.
  Note: DMFs cannot use non-deterministic functions (CURRENT_DATE, CURRENT_TIMESTAMP).
        Date-not-future and DOB-range rules are handled in the orchestration procedure.
=============================================================================*/

USE DATABASE BANKING_DQ_DB;
USE SCHEMA RAW;

-- ============================================================================
-- PART 1: SET DATA METRIC SCHEDULE ON ALL TABLES
-- ============================================================================
ALTER TABLE BRANCHES SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE CUSTOMERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE ACCOUNTS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE TRANSACTIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE LOAN_APPLICATIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- ============================================================================
-- PART 2: CREATE CUSTOM DATA METRIC FUNCTIONS
-- ============================================================================

-- 2.1 IFSC Code format validation (4 alpha + 0 + 6 alphanum)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_IFSC_FORMAT(
  ARG_T TABLE(IFSC_CODE VARCHAR)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE IFSC_CODE IS NOT NULL
    AND NOT RLIKE(IFSC_CODE, '^[A-Z]{4}0[A-Z0-9]{6}$')
$$;

-- 2.2 Email format validation
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_EMAIL_FORMAT(
  ARG_T TABLE(EMAIL VARCHAR)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE EMAIL IS NOT NULL
    AND EMAIL NOT LIKE '%_@_%.__%'
$$;

-- 2.3 Phone format validation (at least 10 digits)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_PHONE_FORMAT(
  ARG_T TABLE(PHONE VARCHAR)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE PHONE IS NOT NULL
    AND LENGTH(REGEXP_REPLACE(PHONE, '[^0-9]', '')) < 10
$$;

-- 2.4 Savings account must have non-negative balance
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_SAVINGS_BALANCE_NON_NEG(
  ARG_T TABLE(ACCOUNT_TYPE VARCHAR, BALANCE NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ACCOUNT_TYPE = 'SAVINGS' AND BALANCE < 0
$$;

-- 2.5 Closed account must have zero balance
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_CLOSED_ZERO_BALANCE(
  ARG_T TABLE(ACCOUNT_STATUS VARCHAR, BALANCE NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ACCOUNT_STATUS = 'CLOSED' AND BALANCE != 0
$$;

-- 2.6 Transaction amount outlier detection (> 10M)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_AMOUNT_RANGE(
  ARG_T TABLE(AMOUNT NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE AMOUNT IS NOT NULL AND AMOUNT > 10000000
$$;

-- 2.7 Approved loan must have approved amount
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_HAS_AMOUNT(
  ARG_T TABLE(APPLICATION_STATUS VARCHAR, APPROVED_AMOUNT NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE APPLICATION_STATUS = 'APPROVED'
    AND APPROVED_AMOUNT IS NULL
$$;

-- 2.8 Approved amount must not exceed requested amount
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_LTE_REQUESTED(
  ARG_T TABLE(APPROVED_AMOUNT NUMBER, REQUESTED_AMOUNT NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE APPROVED_AMOUNT IS NOT NULL
    AND REQUESTED_AMOUNT IS NOT NULL
    AND APPROVED_AMOUNT > REQUESTED_AMOUNT
$$;

-- ============================================================================
-- PART 3: ATTACH SYSTEM DMFs — BRANCHES
-- ============================================================================

-- NULL_COUNT
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_ID);
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_NAME);
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (IFSC_CODE);

-- DUPLICATE_COUNT
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (BRANCH_ID);
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (IFSC_CODE);

-- ROW_COUNT
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- ACCEPTED_VALUES
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    STATE, STATE -> STATE IS NOT NULL AND LENGTH(TRIM(STATE)) > 0);

-- CUSTOM DMF
ALTER TABLE BRANCHES ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_IFSC_FORMAT ON (IFSC_CODE);

-- ============================================================================
-- PART 4: ATTACH SYSTEM DMFs — CUSTOMERS
-- ============================================================================

-- NULL_COUNT
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL);
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PHONE);
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (DATE_OF_BIRTH);

-- DUPLICATE_COUNT
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (EMAIL);

-- ROW_COUNT
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- REFERENTIAL_INTEGRITY_COUNT
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
  ON (BRANCH_ID, TABLE(BANKING_DQ_DB.RAW.BRANCHES(BRANCH_ID)));

-- ACCEPTED_VALUES
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    KYC_STATUS, KYC_STATUS -> KYC_STATUS IN ('VERIFIED','PENDING','REJECTED'));
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    RISK_CATEGORY, RISK_CATEGORY -> RISK_CATEGORY IN ('LOW','MEDIUM','HIGH'));

-- CUSTOM DMFs
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_EMAIL_FORMAT ON (EMAIL);
ALTER TABLE CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_PHONE_FORMAT ON (PHONE);

-- ============================================================================
-- PART 5: ATTACH SYSTEM DMFs — ACCOUNTS
-- ============================================================================

-- NULL_COUNT
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BALANCE);

-- DUPLICATE_COUNT
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ACCOUNT_ID);
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);

-- ROW_COUNT
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- REFERENTIAL_INTEGRITY_COUNT
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
  ON (CUSTOMER_ID, TABLE(BANKING_DQ_DB.RAW.CUSTOMERS(CUSTOMER_ID)));
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
  ON (BRANCH_ID, TABLE(BANKING_DQ_DB.RAW.BRANCHES(BRANCH_ID)));

-- ACCEPTED_VALUES
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    ACCOUNT_TYPE, ACCOUNT_TYPE -> ACCOUNT_TYPE IN ('SAVINGS','CURRENT','LOAN','FD','RD'));
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    ACCOUNT_STATUS, ACCOUNT_STATUS -> ACCOUNT_STATUS IN ('ACTIVE','CLOSED','DORMANT','FROZEN'));
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    CURRENCY, CURRENCY -> CURRENCY IN ('INR','USD','EUR','GBP'));

-- CUSTOM DMFs
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_SAVINGS_BALANCE_NON_NEG ON (ACCOUNT_TYPE, BALANCE);
ALTER TABLE ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_CLOSED_ZERO_BALANCE ON (ACCOUNT_STATUS, BALANCE);

-- ============================================================================
-- PART 6: ATTACH SYSTEM DMFs — TRANSACTIONS
-- ============================================================================

-- NULL_COUNT
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_ID);
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AMOUNT);
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_DATE);

-- DUPLICATE_COUNT
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRANSACTION_ID);

-- ROW_COUNT
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- REFERENTIAL_INTEGRITY_COUNT
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
  ON (ACCOUNT_ID, TABLE(BANKING_DQ_DB.RAW.ACCOUNTS(ACCOUNT_ID)));

-- ACCEPTED_VALUES
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    TRANSACTION_TYPE, TRANSACTION_TYPE -> TRANSACTION_TYPE IN ('CREDIT','DEBIT','TRANSFER','PAYMENT'));
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    TRANSACTION_STATUS, TRANSACTION_STATUS -> TRANSACTION_STATUS IN ('SUCCESS','FAILED','PENDING','REVERSED'));
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    CHANNEL, CHANNEL -> CHANNEL IN ('UPI','NEFT','IMPS','RTGS','CARD','ATM','CHEQUE','BRANCH'));
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    AMOUNT, AMOUNT -> AMOUNT > 0);

-- CUSTOM DMF
ALTER TABLE TRANSACTIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_AMOUNT_RANGE ON (AMOUNT);

-- ============================================================================
-- PART 7: ATTACH SYSTEM DMFs — LOAN_APPLICATIONS
-- ============================================================================

-- NULL_COUNT
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (APPLICATION_ID);
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (REQUESTED_AMOUNT);
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CREDIT_SCORE);

-- DUPLICATE_COUNT
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (APPLICATION_ID);

-- ROW_COUNT
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- REFERENTIAL_INTEGRITY_COUNT
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
  ON (CUSTOMER_ID, TABLE(BANKING_DQ_DB.RAW.CUSTOMERS(CUSTOMER_ID)));
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
  ON (BRANCH_ID, TABLE(BANKING_DQ_DB.RAW.BRANCHES(BRANCH_ID)));

-- ACCEPTED_VALUES
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    APPLICATION_STATUS, APPLICATION_STATUS -> APPLICATION_STATUS IN ('APPROVED','PENDING','REJECTED','CANCELLED'));
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    LOAN_TYPE, LOAN_TYPE -> LOAN_TYPE IN ('HOME','PERSONAL','CAR','EDUCATION','BUSINESS','GOLD'));
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    REQUESTED_AMOUNT, REQUESTED_AMOUNT -> REQUESTED_AMOUNT > 0);
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (
    CREDIT_SCORE, CREDIT_SCORE -> CREDIT_SCORE >= 300 AND CREDIT_SCORE <= 900);

-- CUSTOM DMFs
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_HAS_AMOUNT ON (APPLICATION_STATUS, APPROVED_AMOUNT);
ALTER TABLE LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DMF_APPROVED_LTE_REQUESTED ON (APPROVED_AMOUNT, REQUESTED_AMOUNT);

-- ============================================================================
-- VERIFICATION: Check all attached DMFs
-- ============================================================================
SELECT REF_ENTITY_NAME AS TABLE_NAME, METRIC_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.BRANCHES', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.CUSTOMERS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.ACCOUNTS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.TRANSACTIONS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.LOAN_APPLICATIONS', REF_ENTITY_DOMAIN => 'table'))
ORDER BY TABLE_NAME, METRIC_NAME;

/*=============================================================================
  END OF DQ RULES
=============================================================================*/
